### ISSUE TITLE
Inquiry on Availability of MPC Scores for Latest gnomAD Data

### ISSUE THREAD

**Issue by gmerolli00** [broadinstitute/regional_missense_constraint#310]
Hello RMC Team,

I hope this message finds you well.

I am reaching out to inquire whether the MPC model has been run on the newest gnomAD data. The MPC scores are currently available on the gnomAD site for v2, but I don't see an equivalent tab for v4 (https://gnomad.broadinstitute.org/downloads#v2-regional-missense-constraint). 

Could you please let me know if there are scores for the latest gnomAD data, and if so, whether the updated scores could be made available?

Thank you for your time and assistance. I look forward to hearing from you!

Best regards,  
Giorgia

**Comment by ch-kr** [comment]
Hi Giorgia,

Thanks for reaching out and for your interest in MPC. Regional missense constraint and MPC are not available for v4 yet, and we don't have a timeline/ETA for when the metrics will be ready.

In case it is helpful, we have released a public gnomAD v2 MPC liftover resource (Google URL is `gs://gcp-public-data--gnomad/release/2.1.1/regional_missense_constraint/gnomad_v2.1.1_mpc_liftover_GRCh38.ht`). Note that this resource is not transcript-aware; it was created by lifting over loci from GRCh37 to GRCh38 and retaining the maximum MPC value per locus.

Best,
Katherine

**Comment by gmerolli00** [comment]
Hi Katherine, 

Sounds great, thank you so much for your response!
I hope you have a great day!

Sincerely, 
Giorgia
